// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7kHu_s8sxh0bU1Gr9V3cP7dr3IrBveg',
    appId: '1:509762087423:web:cf2ed500848b0e48c11fca',
    messagingSenderId: '509762087423',
    projectId: 'smartlaba-app',
    authDomain: 'smartlaba-app.firebaseapp.com',
    storageBucket: 'smartlaba-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQsjGViD3eduPatNroiU8-bIRYhJk2QvQ',
    appId: '1:509762087423:android:4a99e8855cff5b58c11fca',
    messagingSenderId: '509762087423',
    projectId: 'smartlaba-app',
    storageBucket: 'smartlaba-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS7kHu_s8sxh0bU1Gr9V3cP7dr3IrBveg',
    appId: '1:509762087423:web:c1a6695ef1214074c11fca',
    messagingSenderId: '509762087423',
    projectId: 'smartlaba-app',
    authDomain: 'smartlaba-app.firebaseapp.com',
    storageBucket: 'smartlaba-app.firebasestorage.app',
  );
}
